### ISSUE TITLE
Ru ALL Wikipedia - is not updated since march 2021

### ISSUE THREAD

**Issue by Ubuntu-2020** [kiwix/web#141] opened 2021-07-12 13:26 UTC
No new versions available **[Ru ALL MAXI](https://download.kiwix.org/zim/wikipedia/)**.
There are only versions for February and March: 
![RU-ALL-MAXI 2021](https://user-images.githubusercontent.com/65112331/125294894-5a1fd080-e32d-11eb-98e4-dd5c4058bad2.png)

There is also a version only for **[March of the current year](https://wiki.kiwix.org/wiki/Content_in_all_languages)**: 
![RU-ALL-MAXI summer 2021](https://user-images.githubusercontent.com/65112331/125294968-6b68dd00-e32d-11eb-9447-a2507cf607bb.png)

**Comment by kelson42** [comment] 2021-07-12 14:36
I confirm, basically a consequence/duplicate of https://github.com/openzim/mwoffliner/issues/1424

**Closed by kelson42** 2021-07-12 14:36 UTC

**Comment by Ubuntu-2020** [comment] 2021-09-19 13:25
@kelson42
I apologize, but so far both the English Wikipedia and the Russian Wikipedia are available only for February and March of the [current year](https://download.kiwix.org/zim/wikipedia/):
![en-all-maxi](https://user-images.githubusercontent.com/65112331/133929180-8500ae38-c9e5-4314-9917-97e5188a3d4a.png)

![ru-all-maxi](https://user-images.githubusercontent.com/65112331/133929192-20f00a60-1bca-49b4-b7c7-af4289ea4e82.png)

**Comment by Popolechien** [comment] 2021-09-19 18:52
@Ubuntu-2020 There are other upstream issues that popped up. Your best best is to check out the recipe runs on the zimfarm and you will see if they are running / when's the last time they failed ([en](https://farm.openzim.org/recipes/wikipedia_en_all). [ru](https://farm.openzim.org/recipes/wikipedia_ru_all)).
