### ISSUE TITLE
Wiki does not update last release date

### ISSUE THREAD

**Issue by Popolechien** [kiwix/web#61] opened 2019-05-14 12:01 UTC
We've had a couple of zim updates already (April & May) yet the wiki still lists content as of last year:
![Capture d’écran 2019-05-14 à 14 00 13](https://user-images.githubusercontent.com/21675885/57696272-ab01e480-7650-11e9-936a-521f781909aa.png)

**Comment by kelson42** [comment] 2019-05-14 12:22
Yes, this is a duplicate of https://github.com/kiwix/maintenance/issues/55

**Closed by kelson42** 2019-05-14 12:22 UTC
Labels: bug
