### ISSUE TITLE
Wiki is down

### ISSUE THREAD

**Issue by Popolechien** [kiwix/web#56] opened 2019-03-06 09:14 UTC
Error message: ``502 Bad Gateway nginx/1.15.8``

Someone else [mentioned](https://framagit.org/ideascube/kiwix-hotspot/issues/309) having a 504 Gateway timeout.

**Comment by kelson42** [comment] 2019-03-15 08:29
I have fixed the incident. I had to rollout a backup image of the container volume (where the data are). The root cause is still unclear. I'm suspicious of this commit https://github.com/openzim/mediawiki-docker/commit/78797cbf576214ca9acc02aa567b07ea9de1adfc. That said, I'm not sure, and I will probably need that the problem appears many times to then remove that commit and see if it works better. @florentk if you have an idea?! In general I think the problem mgmt of this kind is handle within https://github.com/kiwix/maintenance/issues/47. Therefore I will close this ticket. Thank you for reporting it.

**Closed by kelson42** 2019-03-15 08:29 UTC
Labels: bug
