### ISSUE TITLE
Create language-specific versions of library.kiwix.org

### ISSUE THREAD

**Issue by Popolechien** [kiwix/web#28] opened 2017-12-10 20:17 UTC
Too much content available currently on the page as it groups all languages. This is both overwhelming and not too useful. Could it be possible to have library.kiwix.org/es,  /en, /ar etc. so that people can look only at the content available in the language of their choice?

Ideally the next step would be for the icons/boxes to include a small "download zim" link.

**Comment by kelson42** [comment] 2017-12-10 20:21
I think the UI should have a filtering option... That was the first idea...

**Comment by Popolechien** [comment] 2017-12-12 09:44
Ok. Can we then at least restrict the current page to one given language (e.g. English)? Or create pages along the lines of arlibrary.kiwix.org, enlibrary.kiwix.org, frlibrary.kiwix.org, etc.?

**Comment by kelson42** [comment] 2018-01-18 11:38
@Popolechien This is a bit complex. We should really implement the feature to filter things on kiwix-serve.

**Comment by kelson42** [comment] 2018-08-25 16:10
@Popolechien This is a feature request for kiwix-serve, I think quite a duplicate of https://github.com/kiwix/kiwix-tools/issues/220

**Closed by kelson42** 2018-08-25 16:10 UTC
Labels: enhancement
