### ISSUE TITLE
Homepage - Russian - Contact page reirection incorrect

### ISSUE THREAD

**Issue by svikrantaxioned** [kiwix/web#200] opened 2023-02-16 12:45 UTC
Description:
In "Могу ли я просто заказать предварительно заряженную карту или устройство?" section, while clicking on "свяжитесь" it gets redirects in contact page for English language.

Severity:
Major

Priority:
High

Device, OS and Browser Details:
All

Steps To Reproduce:
- Visit the site URL.
- Observe the top header bar.
- Click on Русский.
- Hover on Скачать Kiwix Reader.
- Click on Доступ к карточному магазину.
- Scroll down to Могу ли я просто заказать предварительно заряженную карту или устройство?
- Click on it.
- Hover on свяжитесь.
- Click on it.
- Observe the expected result.

Expected Result:
On clicking on "свяжитесь", respective page should open in the Russian language.

Actual Result:
On clicking on "свяжитесь" it gets redirects in contact page for English language.

Screenshot/Video:
[218395929-bcbabd32-13a7-4b78-ade5-19c8b47ed73c.webm](https://user-images.githubusercontent.com/98155966/219368239-29308e5b-ef60-4cd9-a616-623c58582658.webm)

**Comment by savin8305** [comment] 2023-04-03 16:02
**Expected Result:**
When clicking on "свяжитесь", the respective page should open in the Russian language.

**Actual Result:**
Clicking on "свяжитесь" redirects to the contact page in English language.

This only occurs when the link is redirected in a new tab, not in the same tab.
This issue can be resolved by using a **redirect type**, such as a **301** permanent redirect in server-side configuration, when the URL is clicked.

Alternatively, we can include the **language code** as part of the URL for the contact page **(e.g. http://www.example.com/ru/contact.html)** and ensure that the link for "свяжитесь" points to the Russian contact page URL. This way, when the user clicks on the link, they will be taken directly to the Russian contact page without the need for a redirect type in server-side configuration.

**Comment by Popolechien** [comment] 2023-04-04 08:37
Ok the problem is that we didn't have a page in Russian for contact. Fixed now.

**Closed by Popolechien** 2023-04-04 08:37 UTC
Labels: bug, www.kiwix.org

**Comment by savin8305** [comment] 2023-04-04 09:41
okay thankyou sir
