### ISSUE TITLE
Add date and media type to content packages

### ISSUE THREAD

**Issue by TimJentzsch** [kiwix/web#162] opened 2022-10-21 19:40 UTC
The cards on <https://library.kiwix.org> to download content packages currently provide a very minimal description of the package.

Often, a card appears multiple times with the same title and description, but different download size. It is unclear what the difference is, only taking a peek at the download URL reveals that it is the type of media (maxi/nopic/mini) and date of the archive.

I suggest to add at least the date of the archive and the media type to the cards, so that users can properly decide which package they want to download.

Example:
![Screenshot from the package download page, displaying three seemingly identical cards to download Wikipedia](https://user-images.githubusercontent.com/13908946/197275993-fc8af2c6-7fd9-40f3-a690-d9a394c84773.png)
The three cards for Wikipedia are seemingly identical, the only difference is the download size. In reality, they differ in the media type (maxi/nopic/mini) and date of the archive, as revealed by the download URL.
The difference between nopic and mini is also not apparent.

**Comment by kelson42** [comment] 2022-11-10 11:03
Agree, but this ticket is basically a duplicate of:
* https://github.com/kiwix/web/issues/162
* https://github.com/kiwix/kiwix-tools/issues/551
* https://github.com/openzim/overview/issues/11

**Closed by kelson42** 2022-11-10 11:03 UTC
