### ISSUE TITLE
Library.kiwix.org not including recently created ZIMs

### ISSUE THREAD

**Issue by Popolechien** [kiwix/web#119] opened 2020-06-19 09:34 UTC
aimhi_en_geography_all_2020-06.zim, dicoado_fr_all_maxi_2020-06.zim were both created earlier this month (12 and 13 June, respectively), yet have not made their way to Library.kiwix.org (the zims are available in http://download.kiwix.org/zim/other/

Is there something amiss?

**Comment by kelson42** [comment] 2020-06-19 09:59
Yes, something has been broken.

**Comment by kelson42** [comment] 2020-06-19 10:53
@Popolechien Thx for the bug report

Root cause of the problem is https://github.com/kiwix/kiwix-tools/issues/389. Closing this as duplicated.

I have as well open a ticket so we can detect this lack of update earlier and automatically https://github.com/kiwix/maintenance/issues/140

**Closed by kelson42** 2020-06-19 10:53 UTC
Labels: bug
